### ISSUE TITLE
potential bugs

### ISSUE THREAD

**Issue by fhung65** [jinhofer/pastespecial#3]
I was wondering if the following were integration/usage errors or bugs: (all run on firefox 38.0.1)

From google docs, I copied over a line that started with a bolded word and was otherwise not specifically formatted, and the entire line came out bolded. Upon closer inspection, it turned out that if you copy the entire line in google docs from left to right, google docs was pasting in a "< p style="...">" tag, so the formatting in the < span> tags within it were absorbed into it, and then inherited.
![screenshot from 2015-06-24 17 58 08](https://cloud.githubusercontent.com/assets/9622592/8389305/1901d440-1c23-11e5-891d-347767212f08.png)

From google docs, copying over a word that was half colored and the resulted in output that came out unformatted. changing the "7" in line 578 of button.js ( second "if" condition of _cleanOutput ) to "badSpan + 1" seemed to fix this

![test2](https://cloud.githubusercontent.com/assets/9622592/8389338/99a91cca-1c23-11e5-9597-cb6f295d5aca.png)

From an html file opened in firefox,  I copied "< i>or</ i>" only when this happens?" in, and the word "or" was dropped, in the same line as the above, adding a check for badSpan taking on -1 seemed to fix it.

From libre4.4:
I had text copied in that contained internal css, using < style> tags. This resulted in the rules between the tags showing up as text output.

Libre pasted in text of the form < font color="...">< span style="...">< span style="...">The Text</ span></ span>< /font> This resulted in the text contained getting dropped

**Comment by rlorenzo** [comment]
Was this issue fixed in this commit? https://github.com/jinhofer/pastespecial/commit/d688006adac5b12d136eb8de34c8520e426b9883

**Comment by jinhofer** [comment]
For some reason, I am only now seeing this comment. I'm going to blame it on me being in Europe for three months, though.

I don't think that this commit will fix the issue, since I had not done any work on specifically this issue(s). I will look into these momentarily, though!

**Comment by jinhofer** [comment]
So I've done some poking around with the issues you articulated and I'm either unable to reproduce them, or I'm not completely understanding the issue.

I duplicated your formatting and got a line that APPEARED to be boded and then unbolded, while Atto thought the entire line was bolded. This did not make it look bolded, but Atto thought it was due to the external <b> tag.

I was not able to reproduce this issue. I used the same formatting as you (no background around sentence, then blue background around a half-black, half-red word) but was unable to see any difference between original appearance and appearance of what was pasted. Could you do a screen recording of you pasting this content or something like that?

I not able to reproduce this one either. Which option are you using to paste this text?

Yup, I'm seeing that as well! I've got a fix for both of the Libre issues that'll go in right now. Also worth noting, it brings in the style as well, so the entire page might change some, but only temporarily.

I'm going to make a commit for the Libre issues, and then a separate commit for the other issues once we can figure them out.

**Comment by fhung65** [comment]
Oh, for the half colored word, the blue is my cursor's highlighting, not background color. Though it seems the problem still comes up. Here's the text by itself:
![text](https://cloud.githubusercontent.com/assets/9622592/9503572/a03c13b4-4bec-11e5-908e-b72973b7754e.png)
I copied the word "firefox" which has "fox" colored, and sits in the middle of a sentence.
When I special paste with googledocs option, the color doesn't come out
![test2](https://cloud.githubusercontent.com/assets/9622592/9503617/f13f7350-4bec-11e5-9314-b066d02180f7.png)
![test3](https://cloud.githubusercontent.com/assets/9622592/9503618/f32b17c8-4bec-11e5-8182-02a366ff5084.png)

**Comment by fhung65** [comment]
Also, for the html in firefox, here was my original file, the file opened in firefox, and my paste options,
![testhtml](https://cloud.githubusercontent.com/assets/9622592/9504043/20bcbd3e-4bef-11e5-9cd6-8724b24cd668.png)
And the result: 
![screenshot from 2015-08-26 12 36 19](https://cloud.githubusercontent.com/assets/9622592/9504046/2665260e-4bef-11e5-8d9c-bbf861bff766.png)

**Comment by fhung65** [comment]
Also, the google docs bolding issue seems to have gone away. Perhaps there was an exceptional case the day I initially found that bug, or maybe the way things get pasted over was changed.

**Comment by jinhofer** [comment]
Huh. Here's what I'm seeing for both issues:
![image](https://cloud.githubusercontent.com/assets/8837519/9523179/595c413c-4c9e-11e5-9fab-994ad1d9a349.png)
![image](https://cloud.githubusercontent.com/assets/8837519/9523204/72c10d88-4c9e-11e5-8279-a086a2e87f21.png)

![image](https://cloud.githubusercontent.com/assets/8837519/9523252/ae6ee0da-4c9e-11e5-9ca9-bd7650b4fa9a.png)
![image](https://cloud.githubusercontent.com/assets/8837519/9523262/b7b0e6de-4c9e-11e5-941c-f48276d64f33.png)

Can you include the HTML that you are seeing in the contenteditable 'iframe' div? Also, what theme are you using?

**Comment by fhung65** [comment]
Here's the color issue with the html: 
![send1](https://cloud.githubusercontent.com/assets/9622592/9529253/2004e212-4cae-11e5-8097-a5e65384f1af.png)
![send2](https://cloud.githubusercontent.com/assets/9622592/9529254/20073e04-4cae-11e5-8a02-ed9d3e95a7bc.png)

**Comment by fhung65** [comment]
and here is the italicisation issue: 
![send3](https://cloud.githubusercontent.com/assets/9622592/9529543/c224d13c-4caf-11e5-8b3b-437f8c215930.png)
![send4](https://cloud.githubusercontent.com/assets/9622592/9529544/c227a0f6-4caf-11e5-997b-f484c2d22053.png)

**Comment by fhung65** [comment]
Hm, actually, I tried it on a clean Moodle 3.0 (except the pastespecial plugin), and these problems don't seem to show up. Hm, let me look into it more then.

**Comment by fhung65** [comment]
Oh, my bad, I just updated to the more recent version of the plugin. That's what did it. I'll do some more testing around, but I think those are fixed. Thanks.

**Comment by fhung65** [comment]
Hmm, It seems there is still a bug with MS Word. 
![originalinput](https://cloud.githubusercontent.com/assets/9622592/9637413/6d3a8f40-5155-11e5-8c9f-63e92b4f3144.PNG)

![testinputscreenshot](https://cloud.githubusercontent.com/assets/9622592/9637346/0549d47c-5155-11e5-9a06-8c92cd433fbd.PNG)
![testinputhtml1](https://cloud.githubusercontent.com/assets/9622592/9637354/0c4f6be2-5155-11e5-9c29-f29f512b8120.PNG)
![testinputhtml2](https://cloud.githubusercontent.com/assets/9622592/9637355/0c4fc24a-5155-11e5-8b9e-e0b5246ef154.PNG)
![testresultscreenshot](https://cloud.githubusercontent.com/assets/9622592/9637361/1734ef82-5155-11e5-87f2-f4c5169b89da.PNG)
![testresulthtml](https://cloud.githubusercontent.com/assets/9622592/9637362/1b3ed4b2-5155-11e5-8277-8a4abb74653d.PNG)

**Comment by jinhofer** [comment]
I tried formatting it the same as your example and got this as the HTML for the contenteditable div:
<div id="_atto_pastespecial_iframe" class="atto_pastespecial_iframe" style="width:100%;height:200px;overflow-y:scroll;border: 1px solid grey" contenteditable="true"><span style="font-size:11.0pt;line-height:115%;
font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:
Calibri;mso-fareast-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:&quot;Times New Roman&quot;;mso-bidi-theme-font:minor-bidi;
mso-ansi-language:EN-US;mso-fareast-language:EN-US;mso-bidi-language:AR-SA">Typical
<b style="mso-bidi-font-weight:normal">examples</b> of <i style="mso-bidi-font-style:
normal">formatted</i> <u>text</u> from </span><span class="Heading1Char"><span style="font-size:14.0pt;line-height:115%;mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA">MS Word</span></span><span style="font-size:
11.0pt;line-height:115%;font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;;mso-ascii-theme-font:
minor-latin;mso-fareast-font-family:Calibri;mso-fareast-theme-font:minor-latin;
mso-hansi-theme-font:minor-latin;mso-bidi-font-family:&quot;Times New Roman&quot;;
mso-bidi-theme-font:minor-bidi;mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA">. How much of it does get <span style="background:yellow;mso-highlight:yellow">copied over</span> into ATTO?</span></div>
Which copied over normally.

When I inserted the HTML you supplied:
<div id="_atto_pastespecial_iframe" class="atto_pastespecial_iframe" contenteditable="true" style="width:100%;height:200px;overflow-y:scroll;border: 1px solid grey">
  <p class="MsoNormal" id="yui_3_17_2_2_1441382144053_1475">
    Typical
    <b style="mso-bidi-font-weight:normal">
      examples
    </b>
    of
    <i style="mso-bidi-font-weight:normal">
      formatted
    </i>
    <u>
      text
    </u>
    from
    <b style="mso-bidi-font-weight:normal">
      <span style="font-size:16.0pt;line-height: 107%;font-family:'arial',sans-serif;color:#5b9bd5;mso-themecolor:accent1"="">
        MS
        Word
      </span>
    </b>
    . How much of it does it get
    <span style="background:yellow; mso-highlight:yellow">
      copied over
    </span>
    into ATTO?
  </p>
</div>
It also copied over normally.

I tried this in both Chrome (because I forgot that you were using FF) and then FF and did not notice any issues. I'm not sure what's different between your environment and mine that's causing this.

What computer are you using?
What version of Moodle are you using?
What theme are you using?
Are you using the latest update of pastespecial now?

Those are the only differences that I can think of for now...

**Comment by fhung65** [comment]
Sorry, It turned out to be a version control hiccup on our test server, It seems fine now. Thanks.

**Comment by jinhofer** [comment]
Ah, that would make sense. Thanks for spending so much time working on this! I'm going to close this issue now, but please feel free to open up new issues if you notice any more.
